name: Build and Push Docker Image
on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  IMAGE_NAME: andreysagurov/faq_telegrambot_pelican:latest

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      
      - name: Debug - Check secrets
        run: |
          echo "Username length: ${#DOCKERHUB_USERNAME}"
          echo "Password length: ${#DOCKER_PASSWORD}"
          echo "Username starts with: ${DOCKERHUB_USERNAME:0:3}..."
        env:
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Debug - Check login
        run: |
          echo "Checking Docker auth..."
          cat ~/.docker/config.json | grep -o '"auths":{[^}]*}' || echo "No auth found"
      
      - name: Build and Push Docker Image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${{ env.IMAGE_NAME }}
          provenance: false
      
      - name: Debug - Verify image
        run: |
          echo "Attempting to pull image..."
          docker pull ${{ env.IMAGE_NAME }} || echo "Pull failed"
          echo "Checking Docker Hub..."
          curl -s https://hub.docker.com/v2/repositories/andreysagurov/faq_telegrambot_pelican/tags/ | head -20
          
