name: Build and Deploy to VPS

on:
  push:
    branches:
      - main

env:
  IMAGE_NAME: pelikan-admin

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: andreysagurov/pelikan-admin:latest
  
  deploy:
    runs-on: ubuntu-latest
    needs: build-and-push
    
    steps:
      - name: Deploy to VPS
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          port: 22
          timeout: 300s
          command_timeout: 120s
          script: |
            set -ex
            echo "=== Deployment started at $(date) ==="
            
            cd /opt/pelikan-admin-docker
            echo "Current directory: $(pwd)"
            
            # Git обновление
            echo "Updating code from Git..."
            git fetch origin main --depth=1
            git reset --hard origin/main
            echo "Code updated successfully"
            
            # SSL сертификаты
            echo "Checking SSL certificates..."
            if [ -d privkey.pem ] || [ -d fullchain.pem ]; then
              echo "Removing incorrect directories..."
              rm -rf privkey.pem fullchain.pem
            fi
            
            if [ ! -f privkey.pem ] || [ ! -f fullchain.pem ]; then
              echo "Generating self-signed SSL certificate..."
              openssl req -x509 -newkey rsa:2048 -nodes \
                -keyout privkey.pem \
                -out fullchain.pem \
                -days 365 \
                -subj "/CN=localhost"
              chmod 600 privkey.pem
              chmod 644 fullchain.pem
              echo "SSL certificate created"
            else
              echo "SSL certificates OK"
            fi
            
            mkdir -p data
            
            # Docker операции
            echo "Pulling Docker image..."
            docker pull andreysagurov/pelikan-admin:latest
            
            echo "Stopping old containers..."
            docker-compose down --remove-orphans || true
            
            # Убедиться, что старые контейнеры удалены
            echo "Cleaning up orphan containers..."
            docker ps -a | grep pelikan-admin | awk '{print $1}' | xargs -r docker rm -f || true
            
            sleep 3
            
            echo "Starting new containers..."
            docker-compose up -d --remove-orphans
            
            sleep 5
            
            echo "=== Container Status ==="
            docker-compose ps
            
            echo "=== Recent Logs ==="
            docker-compose logs --tail=30
            
            echo "=== Port Check ==="
            ss -tulpn | grep 8443 || echo "Port not ready yet"
            
            docker image prune -f || true
            
            echo "=== Deployment completed at $(date) ==="
